
export enum ActionType {
  AUTH = "AUTH",
  LOGOUT = "LOGOUT",
  LOGIN_ERROR = "LOGIN_ERROR",
  REGISTER_ERROR = "REGISTER_ERROR",

  ADD_MOVIE = "ADD_MOVIE",
  DISCOVER_MOVIE_LIST = "DISCOVER_MOVIE_LIST",
  MY_MOVIE_LIST = "MY_MOVIE_LIST",

  ADD_ACTOR = "ADD_ACTOR",
  DISCOVER_ACTOR_LIST = "DISCOVER_ACTOR_LIST",
  MY_ACTOR_LIST = "MY_ACTOR_LIST",
  
  DENEME = "DENEME",
}
