export enum ActionType {
  AUTH = "AUTH",
  LOGOUT = "LOGOUT",
  LOGIN_ERROR = "LOGIN_ERROR",
  REGISTER_ERROR = "REGISTER_ERROR",

  // ACTOR ------------
  ADD_ACTOR = "ADD_ACTOR",
  DELETE_ACTOR = "DELETE_ACTOR",
  DISCOVER_ACTOR_LIST = "DISCOVER_ACTOR_LIST",
  MY_ACTOR_LIST = "MY_ACTOR_LIST",
  PUBLISH_ACTOR = "PUBLISH_ACTOR",

  ADD_COMMENT_FOR_ACTOR = "ADD_COMMENT_FOR_ACTOR",
  REMOVE_ACTOR_COMMENT = "REMOVE_ACTOR_COMMENT",

  LIKE_ACTOR = "LIKE_ACTOR",
  REMOVE_LIKE_ACTOR = "REMOVE_LIKE_ACTOR",

  // MOVIE ---------

  ADD_MOVIE = "ADD_MOVIE",
  DELETE_MOVIE = "DELETE_MOVIE",
  DISCOVER_MOVIE_LIST = "DISCOVER_MOVIE_LIST",
  MY_MOVIE_LIST = "MY_MOVIE_LIST",
  PUBLISH_MOVIE = "PUBLISH_MOVIE",

  ADD_COMMENT_FOR_MOVIE = "ADD_COMMENT_FOR_MOVIE",
  REMOVE_MOVIE_COMMENT = "REMOVE_MOVIE_COMMENT",

  LIKE_MOVIE = "LIKE_MOVIE",
  REMOVE_LIKE_MOVIE = "REMOVE_LIKE_MOVIE",
}
